### ISSUE TITLE
nickname is not a unique property

### ISSUE THREAD

**Issue by brendonjohn** [imanhodjaev/django-auth0#5]
In the `Auth0Backend` the authenticate method handles the auth0 payload. 

The username field for users are supposed to be unique. Currently the `nickname` key in the payload is used as the username. This is not suitable as the nickname is not unique.

Example:
- I sign up an account where my email is brendon@numerical.co.nz. Auth0 will provide brendon as the nickname
- Someone else signs up where their email is brendon@newperson. Auth0 will set their nickname to also be brendon.

When the second user attempts to signup, the unique constraint on the username field will be violated and so an error is thrown.

Auth0 gives [two methods](https://auth0.com/docs/user-profile/normalized#uniquely-identify-users) for identifying users. I suggest replacing the use of `nickname` with `user_id`

> This is guaranteed to be unique per user (e.g. {identity provider id}|{unique id in the provider}, or facebook|1234567890).

I'm happy to submit a PR for this

**Comment by sultaniman** [comment]
I see the problem then please decide what you will do with "|" sign because Django will raise validation error with the following message`Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.`.

Code reference: https://github.com/django/django/blob/master/django/contrib/auth/models.py#L306

May be it is good to replace it with `-` or `_` or just normalize email removing `@` sign and other invalid characters.

`Auth0` also has the following thing 

```
"identities": [
    {
      "provider": "google-oauth2",
      "user_id": "103547991597142817347",
      "connection": "google-oauth2",
      "isSocial": true
    }
```

**Comment by brendonjohn** [comment]
> May be it is good to replace it with - or _ 

Lets do this. I'll send a PR and you can decide if you're happy with this 😄
